local opt = vim.opt

opt.autowrite = true -- Enable auto write
opt.clipboard = "unnamedplus" -- Sync with system clipboard
opt.confirm = true -- Confirm to save changes
opt.cursorline = true -- Enable highlighting of the current line
opt.expandtab = true -- Use spaces instead of tabs
opt.formatoptions = "jcroqlnt" -- Automatic formatting "tcqj"
opt.grepformat = "%f:%l:%c:%m" -- Format of grep command output
opt.grepprg = "rg --vimgrep" -- Program to use for grep command
opt.ignorecase = true -- Ignore case
opt.inccommand = "nosplit" -- Preview incremental substitute
opt.laststatus = 0 -- No status line in last window
opt.list = true -- Show invisible characters
opt.mouse = "a" -- Enable mouse mode
opt.number = true -- Show line number
opt.relativenumber = true -- Relative line numbers
opt.scrolloff = 4 -- Lines of context
opt.shiftwidth = 2 -- Size of an indent
opt.showmatch = true -- Show matching bracket
opt.showmode = false -- Don't show mode in statusline
opt.signcolumn = "yes" -- Always show sign column
opt.smartcase = true -- Don't ignore case with capitals
opt.smartindent = true -- Smart indenting on new line
opt.splitbelow = true -- Put new windows below current
opt.splitright = true -- Put new windows right of current
opt.tabstop = 2 -- Size of a tab
opt.termguicolors = true -- True color support
opt.timeoutlen = 300 -- Wait time for mapping to complete
opt.undofile = true -- Save and restore undo history
opt.undolevels = 10000 -- Max number of changes
opt.updatetime = 200 -- Save swap file
opt.wildmode = "longest:full,full" -- Command-line completion mode
opt.wrap = false -- Disable line wrap

